apiVersion: apps/v1
kind: Deployment
metadata:
  name: watermark-app
  namespace: watermark-app
  labels:
    app: watermark-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: watermark-app
  template:
    metadata:
      labels:
        app: watermark-app
    spec:
      containers:
        - name: watermark-app
          image: tauqeerops/gemini-watermark:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
