apiVersion: v1
kind: Service
metadata:
  name: watermark-app
  namespace: watermark-app
  labels:
    app: watermark-app
spec:
  type: NodePort
  selector:
    app: watermark-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
